name: Mi primer github action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo "Hola, mundo!"
